### PR TITLE
Login re style

### PR DESCRIPTION
**Pull request by whitneyklingensmith**
Restyled Login.

### CODE REVIEW

**Comment by bobmccarthy** [comment]
So i see a lot of classNames. I thought our new styling was going to have every button look the same and all text would just be pre-set as paragraph or h2 or whatever. I havnt done any styling so i dont know how true that is. If it looks goo on your side, i'm down. :+1:

**Comment by bobmccarthy** [comment]
Fix merge issues and re-submit. :boom:

**Comment by amicko** [comment]
:+1:

**Comment by m2mathew** [comment]
The description says that you restyled login, but it also appears that the functionality of the QuizListComponent has also been changed. 

What are you adding/changing there?

**Comment by whitneyklingensmith** [comment]
Hey Matt, I had a merge conflict so I just went in to comment out what I had put to get the cohortId.

**Pull request closed without merging**
