### PR TITLE
Reg re style

### PR DESCRIPTION
**Pull request by whitneyklingensmith**
I know that I may not have all the style redo info, but I just wanted to go ahead and get started on this.
I also changed "Jill to Gill" in the registerComponent which to be honset was long over do.

### CODE REVIEW

**Comment by bobmccarthy** [comment]
:+1:

**Comment by suttonofswat** [comment]
dancing

**Comment by suttonofswat** [comment]
what are the merge conflicts?

**Comment by josiahgallen** [comment]
:baby: :muscle:

**Comment by amicko** [comment]
:+1:

**Pull request merged**
