### PR TITLE
Register styling

### PR DESCRIPTION
**Pull request by Moryf1990**
Added a dashboard style and linked it into the main.scss.
Added responsive features to the dashboard component

### CODE REVIEW

**Comment by m2mathew** [comment]
All styling for the components should be nested inside of the class name for that component. This will avoid possible conflicts with the rest of the site.

**Comment by m2mathew** [comment]
In the .scss file, we should all be using nesting to have a single outer layer of class name...

.sass-file-for-this-component {
        // all other styles go inside of here
}

**Comment by Moryf1990** [comment]
Ok, I nested everything inside of the className associated with the div for the entire DashboardComponent. Fixing to to another pull request.

**Comment by m2mathew** [comment]
You don't have to do another pull request. This one is still open!

Just need to push a commit, and it will show up automatically.

**Comment by m2mathew** [comment]
:+1:

**Comment by gbirdjones** [comment]
:+1:

**Comment by jstitts** [comment]
:+1:

**Pull request merged**
