### PR TITLE
Login styles

### PR DESCRIPTION
**Pull request by whitneyklingensmith**

### CODE REVIEW

**Comment by m2mathew** [comment]
I think that they convention that we are using is to put all .scss partials within their own scope.

Like giving the component its own className in JSX and wrapping all styling inside that. This will eliminate potential conflicts in the main.sass.css file once we import

**Comment by m2mathew** [comment]
^^ Though...that is not specifically in the style guide...just helpful.

**Comment by Jmingus** [comment]
Looks Fine

**Comment by m2mathew** [comment]
:100:

**Comment by alarner** [comment]
:+1:

**Pull request merged**
