### PR TITLE
Login styles

### PR DESCRIPTION
**Pull request by whitneyklingensmith**

### CODE REVIEW

**Comment by bobmccarthy** [comment]
get tabs in line to make sure all divs are closed

**Comment by troyacosta** [comment]
In the login js component(lines 48 and 49)  it looks like there may be a couple of closing divs that are out of place.

**Comment by m2mathew** [comment]
I was reading it wrong. nice.
:+1:

**Comment by bobmccarthy** [comment]
got for it :+1:

**Comment by alarner** [comment]
:+1:

**Pull request merged**
