### PR TITLE
added comments and descriptions, corrected tabs

### PR DESCRIPTION
**Pull request by amicko**
We removed the spaces and added tabs, then added descriptive comments to both the quiz results component and the possible answers component.

### CODE REVIEW

**Comment by alarner** [comment]
@amicko Please add some comments at the top of the component that gives a general description of the purpose of the component and what properties (if any) it's expecting to be passed in.

**Comment by amicko** [comment]
@alarner Alright, we added descriptive comments regarding the purpose and needed properties for both the QuizResultsComponent and the PossibleAnswersComponent. Was there anything else we needed, before we merge this to the master?

**Comment by alarner** [comment]
:+1:

**Comment by m2mathew** [comment]
:+1:

**Comment by gbirdjones** [comment]
:+1:

**Pull request merged**
