### PR TITLE
Credits component

### PR DESCRIPTION
**Pull request by m2mathew**
Added the FooterComponent to show on every page.

Added the CreditsComponent to show all student info.

Added styling files for both pieces. (still needs work!)

Fixed style nesting in _style-results.scss.

### CODE REVIEW

**Comment by bobmccarthy** [comment]
:+1:

**Comment by bobmccarthy** [comment]
:+1: :+1:

**Comment by amicko** [comment]
:+1:

**Comment by suttonofswat** [comment]
thumbs up

**Pull request merged**
