### PR TITLE
Styling redo

### PR DESCRIPTION
**Pull request by gmaniago**

### CODE REVIEW

**Comment by bobmccarthy** [comment]
:+1: Will you communicate with Whitney about making sure everyone styling uses the same variable names and such, then communicate to the Front End channel how to appropriately style?

**Comment by whitneyklingensmith** [comment]
Hey Bob, I just didn't have the variables to work with last night. I assumed that I would have to make changes, but just wanted to get started on those because I couldn't finish the cohortId-quiz list. I'm talking with Gladys right now about styling though. So we should be all on the same page styling wise pretty soon!

**Comment by whitneyklingensmith** [comment]
:+1:

**Comment by amicko** [comment]
:+1:

**Pull request merged**
