### PR TITLE
Footer Component

### PR DESCRIPTION
**Pull request by m2mathew**
The footer is now sticking to the bottom of the viewport, as expected.

Also converted some spaces to tabs, per our code standards.

### CODE REVIEW

**Comment by josiahgallen** [comment]
nice

**Comment by gmaniago** [comment]
:+1:

**Comment by bobmccarthy** [comment]
:+1:

**Comment by m2mathew** [comment]
Actually leaving it open and will manually fix the "merge conflicts" real quick

**Comment by bobmccarthy** [comment]
i trust you :+1: too many files to go through

**Comment by gmaniago** [comment]
:+1: you have my faith too.

**Comment by mikeadossi** [comment]
:ok_hand:

**Pull request merged**
