### PR TITLE
teacher name now stays in nav

### PR DESCRIPTION
**Pull request by bobmccarthy**

### CODE REVIEW

**Comment by bobmccarthy** [comment]
:mount_fuji:

**Comment by m2mathew** [comment]
:facepunch:

**Comment by bobmccarthy** [comment]
:ear: :ear_of_rice:

**Comment by bobmccarthy** [comment]
:octocat:

**Comment by josiahgallen** [comment]
:baby: :muscle:

**Comment by suttonofswat** [comment]
thumbs up, arm flex

**Pull request merged**
